/**:
  ros__parameters:
    frame_id: "lidar_2_link"
    sensor_ip: "192.168.1.31"
    host_ip: "192.168.1.10"
    interface_ip: "0.0.0.0"
    host_udp_port: 6060
    channel: 0
    channel_enabled: True
    skip: 1
    angle_start: -1.48
    angle_end: 1.48
    time_offset: -0.07
    general_system_state: True
    derived_settings: True
    measurement_data: True
    intrusion_data: True
    application_io_data: True
    use_persistent_config: False
    min_intensities": 0.0
